name: Deploy KidWatch

on:
  push:
    branches:
      - master
  workflow_dispatch:  # 支持手动触发

env:
  PYTHON_VERSION: "3.11"  # 在顶层定义Python版本

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create config file
        run: |
          mkdir -p kidwatch/config
          echo "${{ secrets.CONFIG_YAML }}" > kidwatch/config/config.yaml

      - name: Deploy files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "kidwatch,requirements.txt"
          target: "${{ secrets.DEPLOY_TARGET }}"
          strip_components: 0

      - name: Setup and install dependencies
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_TARGET }}
            
            # 设置conda的完整路径
            CONDA_PATH="/home/ecs-user/miniconda3/condabin/conda"
            
            # 检查并创建conda环境
            if ! $CONDA_PATH env list | grep -q "kidwatch"; then
              $CONDA_PATH create -n kidwatch python=${{ env.PYTHON_VERSION }} -y
            fi
            
            # 激活环境并安装依赖
            eval "$($CONDA_PATH shell.bash hook)"
            conda activate kidwatch
            pip install -r requirements.txt